apiVersion: install.horusec.io/v2alpha1
kind: HorusecPlatform
metadata:
  name: simplest
  namespace: "${NAMESPACE}"
spec:
  components:
    analytic:
      database:
        host: "${POSTGRESQL_HOST}"
        name: analytic_db
        password:
          secretKeyRef:
            key: postgresql-password
            name: "${ANALYTIC_DB_SECRET_NAME}"
        user:
          secretKeyRef:
            key: postgresql-username
            name: "${ANALYTIC_DB_SECRET_NAME}"
    messages:
      container:
        livenessProbe:
          timeoutSeconds: 3
        readinessProbe:
          timeoutSeconds: 3
      enabled: true
  global:
    broker:
      host: "${RABBITMQ_HOST}"
      password:
        secretKeyRef:
          key: password
          name: "${RABBITMQ_SECRET_NAME}"
      user:
        secretKeyRef:
          key: username
          name: "${RABBITMQ_SECRET_NAME}"
    database:
      host: "${POSTGRESQL_HOST}"
      password:
        secretKeyRef:
          key: postgresql-password
          name: "${PLATFORM_DB_SECRET_NAME}"
      user:
        secretKeyRef:
          key: postgresql-username
          name: "${PLATFORM_DB_SECRET_NAME}"
    jwt:
      secretKeyRef:
        key: secret-key
        name: "${JWT_SECRET_NAME}"
